## Task 1: Unit Converter Program
This program converts units for length, weight and volume using user input.

In [ ]:
# Unit Converter

def unit_converter():
    try:
        print("1. Length")
        print("2. Weight")
        print("3. Volume")

        choice = input("Choose conversion type: ")
        value = float(input("Enter value: "))

        if choice == "1":
            print("1. Meter to Feet")
            print("2. Feet to Meter")
            op = input("Choose option: ")

            if op == "1":
                print("Result:", value * 3.28)

            elif op == "2":
                print("Result:", value / 3.28)

        elif choice == "2":
            print("1. Kg to Pound")
            print("2. Pound to Kg")
            op = input("Choose option: ")

            if op == "1":
                print("Result:", value * 2.2)

            elif op == "2":
                print("Result:", value / 2.2)

        elif choice == "3":
            print("1. Liter to Gallon")
            print("2. Gallon to Liter")
            op = input("Choose option: ")

            if op == "1":
                print("Result:", value * 0.26)

            elif op == "2":
                print("Result:", value / 0.26)

        else:
            print("Invalid choice")

    except:
        print("Invalid input")

unit_converter()

1. Length
2. Weight
3. Volume
Choose conversion type: 1
Enter value: 76
1. Meter to Feet
2. Feet to Meter
Choose option: 1
Result: 249.27999999999997


## Task 2: Mathematical Operations on List
This program calculates sum, average, maximum and minimum values from a list of numbers.

In [ ]:
def find_sum(lst):
    return sum(lst)

def find_avg(lst):
    return sum(lst)/len(lst)

def find_max(lst):
    return max(lst)

def find_min(lst):
    return min(lst)

nums = list(map(int, input("Enter numbers: ").split()))

print("1. Sum")
print("2. Average")
print("3. Max")
print("4. Min")

choice = input("Choose: ")

if choice == "1":
    print(find_sum(nums))

elif choice == "2":
    print(find_avg(nums))

elif choice == "3":
    print(find_max(nums))

elif choice == "4":
    print(find_min(nums))

Enter numbers: 7 8
1. Sum
2. Average
3. Max
4. Min
Choose: 1
15


#List Manipulation
1. Extract every other element

In [ ]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2. Get sublist

In [ ]:
def get_sublist(lst,start,end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3. Reverse list

In [ ]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4. Remove first and last

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5. First n elements

In [ ]:
def get_first_n(lst,n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6. Last 6 elements

In [ ]:
def get_last_n(lst,n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


7. Reverse skip

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


4.3 Exercise on Nested List
1 Flatten Nested List

In [1]:
def flatten(lst):
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2 Access Nested Element

In [2]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


3 Sum of Nested List

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

4 Remove Element from Nested List

In [3]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5 Find Maximum Element

In [4]:
def find_max(lst):
    maximum = float('-inf')

    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


6. Count Occurrences

In [5]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


7 Deep Flatten

In [6]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8 Nested List Average

In [ ]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

# NumPy Problems

In [ ]:
import numpy as np

Task 1: Array Creation

In [ ]:
# empty 2x2
a = np.empty((2,2))

# ones 4x2
b = np.ones((4,2))

# full array
c = np.full((3,3),7)

# zeros like
d = np.zeros_like(c)

# ones like
e = np.ones_like(c)

# list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)

print(a,b,c,d,e,f)

[[1.64686091e-315 0.00000000e+000]
 [1.64727115e-315 1.64727115e-315]] [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] [[7 7 7]
 [7 7 7]
 [7 7 7]] [[0 0 0]
 [0 0 0]
 [0 0 0]] [[1 1 1]
 [1 1 1]
 [1 1 1]] [1 2 3 4]


Task 2: Array Manipulation

In [ ]:
# 10 to 49
a = np.arange(10,50)

# 3x3 matrix
b = np.arange(9).reshape(3,3)

# identity
c = np.eye(3)

# random array mean
d = np.random.random(30)
print(d.mean())

# 10x10 random min max
e = np.random.random((10,10))
print(e.min(),e.max())

# zero array replace
f = np.zeros(10)
f[4] = 1

# reverse array
arr = np.array([1,2,0,0,4,0])
print(arr[::-1])

# border array
g = np.ones((5,5))
g[1:-1,1:-1] = 0

# checkerboard
h = np.zeros((8,8))
h[1::2,::2] = 1
h[::2,1::2] = 1

print(a,b,c,f,g,h)

0.5018247579751622
0.0060506687080756905 0.9895027432445038
[0 4 0 0 2 1]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] [[0 1 2]
 [3 4 5]
 [6 7 8]] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.] [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Task 3: Array Operations

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# addition
print(x + y)

# subtraction
print(x - y)

# multiply with integer
print(x * 2)

# square
print(x**2)

# dot products
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

# concatenate
print(np.vstack((x,y)))
print(np.column_stack((v,w)))

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


Task 4: Matrix Operations

In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# A * A^-1
A_inv = np.linalg.inv(A)
print(np.dot(A,A_inv))

# AB != BA
print(np.dot(A,B))
print(np.dot(B,A))

# (AB)^T = B^T A^T
print(np.transpose(np.dot(A,B)))
print(np.dot(B.T,A.T))

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


Linear Equation Solver

In [ ]:
A = np.array([[2,-3,1],
              [1,-1,2],
              [3,1,-1]])

B = np.array([-1,-3,9])

X = np.linalg.inv(A).dot(B)

print("Solution:",X)

Solution: [ 2.  1. -2.]


Performance Experiment (NumPy vs Python)

In [ ]:
import time
import numpy as np

size = 1000000

a = list(range(size))
b = list(range(size))

# Python list addition
start = time.time()
c = [a[i] + b[i] for i in range(size)]
print("List addition time:", time.time()-start)

# numpy addition
a_np = np.array(a)
b_np = np.array(b)

start = time.time()
c = a_np + b_np
print("Numpy addition time:", time.time()-start)

List addition time: 0.12432169914245605
Numpy addition time: 0.024072647094726562
